version: '1.0'

# THESE OVERRIDES ARE FOR DEVELOPMENT! DON'T USE THIS IN PRODUCTION!
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
  app:
    command: >
        sh -c "python manage.py makemigrations User Contract Job Message Payment Proposal &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
  celery:
    environment:
      - DEBUG=True