version: '1.0'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  app:
    command: >
        sh -c "python manage.py makemigrations User Contract Job Message Payment Proposal &&
               python manage.py migrate &&
               python manage.py runsslserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
  celery:
    environment:
      - DEBUG=True